sshward: reorganize options, forward_arguments, hosts, etc.

diff --git a/sshward b/sshward
--- a/sshward
+++ b/sshward
@@ -1,9 +1,11 @@
 #!/bin/bash
 
-rhost=tkynt2
-rport=50522
-lport=22
-htime=300
+function mkd {
+  while (($#)); do
+    [[ -d $1 ]] || mkdir -p "$1"
+    shift
+  done
+}
 
 #
 # tkynt2 port table
@@ -20,39 +22,27 @@ htime=300
 # USAGE:
 #
 # laguerre <- rcnp
-#   sshdfwd.20130310 -l20002 ftp-a.rcnp:50322 -Stcsh &>/dev/null &
+#   sshward.20130310 -l20002 ftp-a.rcnp:50322 -Stcsh &>/dev/null &
 # yogo <- rcnp
-#   sshdfwd.20130310 ftp-a.rcnp:50422 -Stcsh &>/dev/null &
+#   sshward.20130310 ftp-a.rcnp:50422 -Stcsh &>/dev/null &
 #
 
 shell=bash
-fwddir=$HOME/bin/sshdfwd.d
+prefix=$HOME/.mwg/share/sshward
+mkd "$prefix/tmp" "$prefix/log"
 
+declare -a forward_options ssh_options
 ssh_options=()
+forward_options=(-n)
 
-while (($#)); do
-  declare arg="$1"
-  shift
-  case "$arg" in
-  (-i)   ssh_options+=(-i "$1"); shift ;;
-  (-i*)  ssh_options+=(-i "${arg:2}") ;;
-  (-l?*) lport="${arg:2}" ;;
-  (-S?*) shell="${arg:2}" ;;
-  (-H?*)
-    # heart beat time
-    htime="${arg:2}" ;;
-  (*:*)
-    rhost="${arg%:*}"
-    rport="${arg##*:}"
-    ;;
-  esac
-done
+rhost=tkynt2
 
-function fileage {
-  local now="$(date +%s)"
-  local mtime="$(ls -ld --time-style=+%s "$1" 2>/dev/null | awk '{print $6;exit}')"
-  echo $((now-mtime))
-}
+# heart beat time
+htime=300
+
+fTitle=
+oTitle=
+oHost=
 
 # http://www.debianadmin.com/howto-use-ssh-local-and-remote-port-forwarding.html
 #
@@ -67,23 +57,133 @@ function fileage {
 #   clientspecified は -R bind_address:rport:localhost:lport の bind_address に指定された内容を使うことを表す。
 #   GatewayPorts yes は全ての interface に bind する事を表す。
 #
-declare forward_options=(-nR "*:$rport:localhost:$lport")
+
+function read_arguments/error {
+  echo "${0##*/} ($pos): $*" >&2
+  fError=1
+}
+
+function read_arguments/option:H {
+  if [[ $1 =~ ^[0-9]+$ ]]; then
+    htime="$1"
+  else
+    if (($#==0)); then
+      read_arguments/error "missing option argument."
+    else
+      read_arguments/error "invalid option argument \`$1'."
+    fi
+  fi
+}
+
+function read_arguments/option:help {
+  local tvar='[36m' t0='[m'
+  local tpat='[91m'
+  local OPTION="${tvar}OPTION${t0}"
+  local FORWARD="${tvar}FORWARD${t0}"
+  local svar="${tvar}@${t0}"
+  ifold -i -s -w 80 <<EOF
+usage: ${0##*/} ${tpat}[${t0}$OPTION${tpat}...]${t0} ${tpat}[${t0}$FORWARD${tpat}...]${t0} ${tvar}HOST${t0}
+
+$OPTION
+
+  --help
+  -i ${svar/@/IdentityFile}
+  -H ${svar/@/HeartbeatInterval}
+  --title=${svar/@/TITLE}
+
+  -Ws,${svar/@/SSHOPTIONS}
+  -Wf,${svar/@/SSHOPTIONS}
+    These options can be used to specify SSH options directly. \
+The options with \`-Ws' will be used to create ssh connection. \
+The options with \`-Wf' will be used to make port fowardings. \
+While the \`-Wf' options are used only on making port forwardings, \
+the \`-Ws' options are used whenever ssh connections are needed, e.g. on installation of heartbeat scripts to the ${svar/@/HOST}.
+
+$FORWARD
+
+  ${tpat}[${t0}${tvar}RHOST${t0}:${tpat}]${t0}${tvar}RPORT${t0}>${tpat}[${t0}${tvar}LHOST${t0}:${tpat}]${t0}${tvar}LPORT${t0}
+    Remort Port Forwarding
+
+  ${tpat}[${t0}${tvar}RHOST${t0}:${tpat}]${t0}${tvar}RPORT${t0}<${tpat}[${t0}${tvar}LHOST${t0}:${tpat}]${t0}${tvar}LPORT${t0}
+    Local Port Forwarding
+
+EOF
+  exit 0
+}
+
+function read_arguments {
+  while (($#)); do
+    local arg="$1" pos="command line argument \`$1'"
+    shift
+    case "$arg" in
+    (-i)   ssh_options+=(-i "$1"); shift ;;
+    (-i*)  ssh_options+=(-i "${arg:2}") ;;
+    (-H)   read_arguments/option:H "$@"; shift ;;
+    (-H*)  read_arguments/option:H "${arg:2}" ;;
+    (-Wf,*) IFS=, eval 'forward_options+=(${arg%-Ws,})' ;;
+    (-Ws,*) IFS=, eval 'ssh_options+=(${arg%-Ws,})' ;;
+    (--help) read_arguments/option:help ;;
+    (--title=*)
+      fTitle=1 oTitle=${arg#*=} ;;
+    (*'>'*)
+      local rhost=${arg%%\>*}
+      [[ $rhost != *:* ]] && rhost=*:$rhost
+      local lhost=${arg#*\>}
+      [[ $lhost != *:* ]] && lhost=localhost:$lhost
+      forward_options+=(-R "$rhost:$lhost")
+      [[ $fTitle ]] || oTitle+=" R($arg)" ;;
+    (*'<'*)
+      local rhost=${arg%%\<*}
+      [[ $rhost != *:* ]] && rhost=localhost:$rhost
+      local lhost=${arg#*\<}
+      [[ $lhost != *:* ]] && lhost=*:$lhost
+      forward_options+=(-L "$lhost:$rhost")
+      [[ $fTitle ]] || oTitle+=" L($arg)" ;;
+    (?*)
+      if [[ ! $oHost ]]; then
+        oHost=$arg
+      else
+        read_arguments/error 'multiple hosts are specified.'
+      fi ;;
+    (*)
+      read_arguments/error 'unrecognized argument.' ;;
+    esac
+  done
+}
+
+read_arguments "$@"
+
+if [[ ! $oHost ]]; then
+  local pos='command line'
+  read_arguments/error 'no host is specified.'
+fi
+
+[[ $fError ]] && exit 1
+
+function fileage {
+  local now="$(date +%s)"
+  local mtime="$(ls -ld --time-style=+%s "$1" 2>/dev/null | awk '{print $6;exit}')"
+  echo $((now-mtime))
+}
 
 (
-  function sshdfwd/start-heartbeat {
-    local script='$HOME/.mwg/share/sshdfwd/heartbeat.v0.sh'
-    local ssh_out="$(LANG=C ssh "${ssh_options[@]}" "${forward_options[@]}" "$rhost" "\"$script\" $htime --from=$HOSTNAME" 2>&1; ret=$?; echo exit=$ret)"
+  function sshward/ssh {
+    LANG=C ssh "${ssh_options[@]}" "${forward_options[@]}" "$oHost" "\"$script\" $htime --from=$HOSTNAME"
+  }
+
+  function sshward/start-heartbeat {
+    local script='$prefix/heartbeat.v0.sh'
+    local ssh_out="$(sshward/ssh 2>&1; ret=$?; echo exit=$ret)"
     local ret="$?"
     if [[ $ssh_out =~ exit=127 || $ssh_out =~ "/heartbeat.v0.sh: Command not found" ]]; then
-      sshdfwd/log "installing scripts to remote host ($script)."
+      sshward/log "installing scripts to remote host ($script)."
       # 向こうにスクリプトが存在しなかった時に、インストールする
-      ssh "${ssh_options[@]}" "$rhost" "mkdir -p \"${script%/*}\" && cat >> \"$script\" && chmod +x \"$script\"" <<'EOF' && \
-        ssh "${ssh_options[@]}"  "${forward_options[@]}" "$rhost" "\"$script\" $htime --from=$HOSTNAME"
+      ssh "${ssh_options[@]}" "$oHost" "mkdir -p \"${script%/*}\" && cat >> \"$script\" && chmod +x \"$script\"" <<'EOF' && sshward/ssh
 #!/bin/sh
 
 # kill other
 ps ax -o ppid,pid,user,command \
-  | awk '$1=="1"&&$3=="'"$USER"'"&&$0~/\/\.mwg\/share\/sshdfwd\/[h]eartbeat.v[0-9]+.sh\y|\ybash -c while :; do date; sleep [0-9]+; done$/{print "kill",$2;}' \
+  | awk '$1=="1"&&$3=="'"$USER"'"&&$0~/\/\.mwg\/share\/sshward\/[h]eartbeat.v[0-9]+.sh\y|\ybash -c while :; do date; sleep [0-9]+; done$/{print "kill",$2;}' \
   | sh
 
 htime="$1"
@@ -100,19 +200,19 @@ EOF
     fi
   }
 
-  function sshdfwd/log {
-    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" >> "$HOME/bin/sshd_forward.log"
+  function sshward/log {
+    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" >> "$prefix"/log/sshward.log
   }
 
   nfail=0
-  ftouch="$fwddir/connect.touch"
+  ftouch="$prefix"/tmp/sshward.$$.touch
   while :; do
     touch "$ftouch"
-    sshdfwd/log "try sshfwd localhost:$lport <- $rhost:$rport"
-    sshdfwd/start-heartbeat >> $fwddir/sshdfwd.err 2>&1
+    sshward/log "try sshward $oTitle"
+    sshward/start-heartbeat >> "$prefix"/log/sshward.err 2>&1
 
     jizoku=$(fileage "$ftouch")
-    sshdfwd/log "failed jizoku=$jizoku"
+    sshward/log "failed jizoku=$jizoku"
     ((nfail=jizoku<300?nfail+1:0))
 
     sleep $((300+(nfail<30?nfail:30)*600))
